version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: andrea_jimenez
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: riki123
    ports:
      - "5432:5432"   # si quieres conectar desde fuera del contenedor

  web:
    build: .
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app                     # Código local sincronizado con contenedor
      - media_volume:/app/media    # Archivos media persistentes
      - static_volume:/app/staticfiles  # Archivos estáticos persistentes
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"               # Modo desarrollo
      DB_HOST: db
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
  media_volume:
  static_volume: 