# Generated by Django 5.2.5 on 2026-03-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0012_cupondescuento_pedido_ciudad_pedido_costo_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
